### ISSUE TITLE
Info required

### ISSUE THREAD

**Issue by mkhizeryounas** [iam-mhaseeb/EDA-on-Retail-Data#1]
@iam-mhaseeb Please explain what does it do and what prediction or analysis it runs. It maybe helpful to me.

**Comment by mkhizeryounas** [comment]
# @

- [ ] 

- [1. ](`

> **_**url**_**

`)

**Comment by iam-mhaseeb** [comment]
This is analysis on retail deta open sourced by data.world. I tried to extract useful information from data & figured it out which store, dept & category got most sales. The most important & interesting one why they got most sales.
This is how this EDA works man!

**Comment by iam-mhaseeb** [comment]
I'm closing it for now, if you want to learn more please reopen it.
